export const KEY_RING = [
  { c: '#FFBB33', key: 'level1Completed' },
  { c: '#4B0082', key: null },
  { c: '#DC143C', key: null },
  { c: '#00FF88', key: null },
  { c: '#FFFFFF', key: null },
];

export function buildTrainingModules({ level1Completed, handleTutorial, handleLevel1, handleCredits }) {
  return [
    {
      id: 'tutorial',
      idx: '00',
      icon: 'tutorial',
      title: 'TUTORIAL',
      subtitle: 'Sala de Entrenamiento',
      desc: 'Aprende los controles básicos: movimiento, cámara, salto y sprint en un entorno 3D seguro.',
      color: '#00F0FF',
      status: 'available',
      action: handleTutorial,
      disabled: false,
    },
    {
      id: 'level1',
      idx: '01',
      icon: 'level',
      title: 'NIVEL 1',
      subtitle: 'Las Cenizas de la Ciudad',
      desc: 'Explora la Ciudad Neón, resuelve 3 puzzles, encuentra recuerdos y obtén la Llave Ámbar.',
      color: '#FFBB33',
      keyColor: '#FFBB33',
      keyName: 'LLAVE ÁMBAR',
      status: level1Completed ? 'completed' : 'available',
      action: handleLevel1,
      disabled: false,
    },
    {
      id: 'level2',
      idx: '02',
      icon: 'soon',
      title: 'NIVEL 2',
      subtitle: 'El Libro que Falta',
      desc: 'Mundo: Biblioteca de Halliday — Zona de Memoria.',
      color: '#4B0082',
      keyColor: '#4B0082',
      keyName: 'LLAVE ÍNDIGO',
      status: 'soon',
      action: null,
      disabled: true,
    },
    {
      id: 'level3',
      idx: '03',
      icon: 'soon',
      title: 'NIVEL 3',
      subtitle: 'Arena del Silencio',
      desc: 'Mundo: Coliseo Carmesí — Zona de Combate.',
      color: '#DC143C',
      keyColor: '#DC143C',
      keyName: 'LLAVE CARMESÍ',
      status: 'soon',
      action: null,
      disabled: true,
    },
    {
      id: 'level4',
      idx: '04',
      icon: 'soon',
      title: 'NIVEL 4',
      subtitle: 'Jardín de Cristal',
      desc: 'Mundo: Bosque Esmeralda — Zona de Cooperación.',
      color: '#00FF88',
      keyColor: '#00FF88',
      keyName: 'LLAVE ESMERALDA',
      status: 'soon',
      action: null,
      disabled: true,
    },
    {
      id: 'level5',
      idx: '05',
      icon: 'soon',
      title: 'NIVEL 5',
      subtitle: 'El Último Código',
      desc: 'Mundo: Torre Blanca — Zona Final.',
      color: '#FFFFFF',
      keyColor: '#FFFFFF',
      keyName: 'LLAVE BLANCA',
      status: 'soon',
      action: null,
      disabled: true,
    },
    {
      id: 'credits',
      idx: '★',
      icon: level1Completed ? 'credits' : 'locked',
      title: 'CRÉDITOS',
      subtitle: 'El Equipo OASIS',
      desc: level1Completed
        ? 'Conoce al equipo detrás del OASIS. Tecnologías, patrones de diseño y más.'
        : 'Completa el Nivel 1 para desbloquear los créditos del equipo.',
      color: '#FF61D8',
      status: level1Completed ? 'available' : 'locked',
      action: handleCredits,
      disabled: !level1Completed,
    },
  ];
}
